import os

SECRET_KEY = os.getenv("SUPERSET_SECRET_KEY", "PLEASE_CHANGE_ME")
ENABLE_PROXY_FIX = True
ROW_LIMIT = 5000

# Priorizar Postgres en el modal de nueva BD
PREFERRED_DATABASES = ["PostgreSQL"]

ALERT_REPORT_TABS = True
DATE_RANGE_TIMESHIFTS_ENABLED = True
ENABLE_ADVANCED_DATA_TYPES = True
PRESTO_EXPAND_DATA = True
TAGGING_SYSTEM = True
CHART_PLUGINS_EXPERIMENTAL = True

ALERT_REPORTS = True
ALLOW_FULL_CSV_EXPORT = True
CACHE_IMPERSONATION = False
CONFIRM_DASHBOARD_DIFF = False
DYNAMIC_PLUGINS = True
DATE_FORMAT_IN_EMAIL_SUBJECT: True
ENABLE_SUPERSET_META_DB: True
ESTIMATE_QUERY_COST = False
GLOBAL_ASYNC_QUERIES = True
IMPERSONATE_WITH_EMAIL_PREFIX = True
PLAYWRIGHT_REPORTS_AND_THUMBNAILS = True


ALERTS_ATTACH_REPORTS = True
ALLOW_ADHOC_SUBQUERY = True
DASHBOARD_RBAC = True
DATAPANEL_CLOSED_BY_DEFAULT = False
DRILL_BY = True
DRUID_JOINS = True
EMBEDDABLE_CHARTS = True
EMBEDDED_SUPERSET = True
ENABLE_TEMPLATE_PROCESSING = True
LISTVIEWS_DEFAULT_CARD_VIEW = True
SCHEDULED_QUERIES  = True
SQLLAB_BACKEND_PERSISTENCE = True
THUMBNAILS = True
